void main(){
  // int sum=0;
  // List list = [1,23,4,5,6,7,8,9,10];
  // for(int i in list){
  //   sum=sum+i;

  // }
  // print(sum);


  //---------------------------------------------------
  // List list2 = [100,23,4,5,600,7,8,9,102];
  // int greatestNum = list2[0];
  // for(int j=0;j< list2.length ; j++){
    
  //   if (list2[j]>greatestNum){
  //     greatestNum = list2[j];

  //   }
  // }
  // print(greatestNum);

  //--------------------------------------------------------------
  //Write a Dart program to find the index of a specific element in a list using a for loop.


}